version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: reactive-postgres2
    ports:
      - "5433:5432"   # host:container
    environment:
      POSTGRES_DB: reactive_db2
      POSTGRES_USER: reactive_user2
      POSTGRES_PASSWORD: reactive_pass2
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
