services:
  postgres:
    image: postgres:16
    container_name: reactive-postgres2
    ports:
      - "5433:5432"   # host:container
    environment:
      POSTGRES_DB: reactive_db2
      POSTGRES_USER: reactive_user2
      POSTGRES_PASSWORD: reactive_pass2
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: pulsar2
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650"   # Pulsar binary protocol
      - "8081:8080"   # Pulsar Admin / UI
    volumes:
      - pulsar-data:/pulsar/data
    restart: unless-stopped

volumes:
  postgres_data:
  pulsar-data:
