spring:
#  application:
#    name: spring-reactive-kotlin

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/reactive_db2
    user: reactive_user2
    password: reactive_pass2

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/reactive_db2
    username: reactive_user2
    password: reactive_pass2

  pulsar:
    client:
      service-url: pulsar://localhost:6650

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.spring_reactor2: DEBUG
    org.springframework.r2dbc: INFO
    org.apache.pulsar: INFO
    org:
      flywaydb=DEBUG:
